on: [push, pull_request]

name: MPI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            mpi: openmpi
          - os: macos-latest
            rust: stable
            mpi: openmpi
          - os: windows-2022
            rust: stable
            mpi: msmpi
            
    name: ${{ matrix.os }} example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - run: mpicc helloworld.c -o helloworld
      - run: mpiexec -n 2 ./helloworld